#!/usr/bin/env bash
set -euo pipefail

# ── Post-provision hook ─────────────────────────────────────────────
# Runs after `azd provision` to populate .env with provisioned values.

echo "==> Post-provision: writing .env from azd outputs..."

ENDPOINT=$(azd env get-value endpoint 2>/dev/null || true)
BING_CONN=$(azd env get-value bingConnectionId 2>/dev/null || true)
MODEL=$(azd env get-value deploymentName 2>/dev/null || true)

cat > .env <<EOF
# Auto-generated by hooks/postprovision.sh – do not edit manually
AZURE_AI_ENDPOINT=${ENDPOINT}
BING_CONNECTION_ID=${BING_CONN}
MODEL_NAME=${MODEL:-gpt-4o}
EOF

echo "==> .env written successfully."
